idle_bg = "#00000000"
idle_fg = "#b9b9b9"
info_bg = "#00000000"
info_fg = "#b9b9b9"
good_bg = "#00000000"
good_fg = "#b9b9b9"
warning_bg = "#00000000"
warning_fg = "#b9b9b9"
critical_bg = "#00000000"
critical_fg = "#b9b9b9"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
