################################### bindings ###################################

# prefix key
set -g prefix C-b

# reload .tmux.conf
bind R source-file ~/.config/tmux/tmux.conf \; display "configuration reloaded"

# keep PWD when creating new panes/windows
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# join target pane into current window
bind + command-prompt "join-pane -t :. -s '%%'"

# mouse support
bind m set -g mouse

# show activity in windows
bind a set -g monitor-activity

# enable scrolling with the mouse
bind -T root WheelUpPane select-pane -t = \; copy-mode -t = \; send-keys -M
bind -T root WheelDownPane select-pane -t = \; copy-mode -t = \; send-keys -M

# vi break current pane into new window
bind T break-pane

# vi tree chooser
bind E choose-tree

# vi pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#################################### server #################################### 

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -gs escape-time 10
set -g message-limit 1000

################################### session #################################### 

set -g base-index 1
set -g display-panes-active-colour blue
set -g display-panes-colour brightyellow
set -g display-panes-time 3000
set -g display-time 3000
set -g message-command-style fg=black,bg=brightyellow
set -g message-style fg=black,bg=brightyellow
set -g renumber-windows on
set -g status on
set -g status-interval 1
set -g status-justify centre
set -g status-keys vi
set -g status-position bottom
set -g status-left "#[bg=white]#[fg=black] #S:#I.#P#{?monitor-activity, 󰂚,}#{?mouse, ,}#[fg=white]#[bg=default]"
set -g status-right "#[fg=white,bg=default]#[fg=black,bg=white]󰃰 %a %d.%m %R"
set -g status-left-length 50
set -g status-right-length 50
set -g status-style bg=default

#################################### window ####################################

setw -g allow-rename on
setw -g clock-mode-colour brightyellow
setw -g clock-mode-style 24
setw -g mode-keys vi
setw -g mode-style fg=white,bg=brightyellow
setw -g pane-active-border-style fg=blue
setw -g pane-base-index 1
setw -g pane-border-style fg=white
setw -g window-status-activity-style fg=red
setw -g window-status-bell-style fg=red
setw -g window-status-current-format "#[fg=blue]#[fg=black]#[bg=blue]#I#{?#{m:*Z,#{window_flags}},󰊓,}#[fg=blue]#[bg=white]#[fg=black] #W#[fg=white]#[bg=default]"
setw -g window-status-format "#{?window_activity_flag,#[fg=red]#[bg=red],#[fg=brightblack]#[bg=brightblack]}#[fg=brightwhite]#I#{?#{m:*Z,#{window_flags}},󰊓,}#[bg=white]#{?window_activity_flag,#[fg=red],#[fg=brightblack]}#[fg=brightwhite] #W#[fg=white]#[bg=default]"

# vim: ft=tmux
